require("options")
require("keymaps")

require("config.ui")
require("config.lazy")
require("config.nvim-tree")
require("config.treesitter")
require("config.lsp")
require("config.go")
require("config.python")
require("config.neogit")
