require "plugins"
require "options"
require "keymaps"

require "conf.bufferline"
require "conf.cmp"
require "conf.dap"
require "conf.go"
require "conf.lsp"
require "conf.sumneko_lua"
require "conf.lualine"
require "conf.neotest"
require "conf.nvim-tree"
require "conf.python"
require "conf.rust"
require "conf.telescope"
require "conf.treesitter"
